AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  base

  Sample SAM Template for base

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    Runtime: nodejs14.x
    Architectures:
      - x86_64
    CodeUri: src/

Resources:
  # get card function
  GetCardFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.getCardHandler
      Events:
        GetCard:
          Type: Api
          Properties:
            Path: /cards
            Method: get
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - app.ts

  # update card function
  UpdateCardFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.updateCardHandler
      Events:
        UpdateCard:
          Type: Api
          Properties:
            Path: /cards/{id}
            Method: put
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - app.ts

  # create card function
  CreateCardFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.createCardHandler
      Events:
        CreateCard:
          Type: Api
          Properties:
            Path: /cards
            Method: post
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - app.ts

  # delete card function
  DeleteCardFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.deleteCardHandler
      Events:
        DeleteCard:
          Type: Api
          Properties:
            Path: /cards/{id}
            Method: delete
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - app.ts
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
