@endpoint = https://crryyv9u6a.execute-api.eu-west-1.amazonaws.com/prod

GET {{endpoint}}/hello
###

POST {{endpoint}}/spaces
Content-Type: application/json

{
  "location": "Paris",
  "name": "Romantic Location"
}
###